/zs_x11:
  ros__parameters:
    ~max_speed: 50
    ~scale_speed: 50
/left_wheel:
  ros__parameters:
    ~max_speed: 50
    ~scale_speed: 50
    wheel_topic: lwheel
    motor_cmd_topic: lmotor_cmd
    pwm_pin: 13
    reverse_pin: 6
    brake_pin: 26
/right_wheel:
  ros__parameters:
    ~max_speed: 50
    ~scale_speed: 50
    wheel_topic: rwheel
    motor_cmd_topic: rmotor_cmd
    pwm_pin: 12
    reverse_pin: 5
    brake_pin: 25
