/twist_to_motors_node:
  ros__parameters:
    twist_topic: cmd_vel
    lwheel_vtarget_topic: lwheel_vtarget
    rwheel_vtarget_topic: rwheel_vtarget,
/left_wheel:
  ros__parameters:
    wheel_topic: lwheel
    motor_cmd_topic: lmotor_cmd
    wheel_vtarget_topic: lwheel_vtarget
    pwm_pin: 13
    reverse_pin: 6
    brake_pin: 26
    speed_pulse_pin: 16
/right_wheel:
  ros__parameters:
    wheel_topic: rwheel
    motor_cmd_topic: rmotor_cmd
    wheel_vtarget_topic: rwheel_vtarget
    pwm_pin: 12
    reverse_pin: 5
    brake_pin: 25
    speed_pulse_pin: 19
    inverse_direction: True
