teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0 
    scale_linear_turbo:
      x: 2.0

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 1.0

    require_enable_button: false
    enable_button: 8  # L2 shoulder button
    enable_turbo_button: 10  # L1 shoulder button

